<!-- <div class="container">
    <div class="contact__title">
        <span>contact us</span>
    </div>
    <div class="contact__icon">
        <div class="contact__icon--icon">
            <li><i class="fas fa-comment"></i></li>
            <li>chat</li>
        </div>
        <div class="contact__icon--icon">
            <li><i class="fas fa-phone-alt"></i></li>
            <li>call</li>
        </div>
        <div class="contact__icon--icon">
            <li><i class="fas fa-envelope"></i></li>
            <li>email</li>
        </div>
    </div>
    <div class="contact__bottom">
        <li>0800 808 5745 Mon-Eri ,24/24(Tool Free)</li>
        <li>service@glamira.co.uk</li>
    </div>
</div> -->