<?php
/**
* Copyright © 2013-2017 Magento, Inc. All rights reserved.
* See COPYING.txt for license details.
*/
// @codingStandardsIgnoreFile
?>

<div class="header_top container">
    <div class="header_top__FreeShip ">
        <span class="icon-struck"><i class="fa fa-truck" aria-hidden="true"></i></span>
        <span class="text-freeshipp">Free Shipping</span>
    </div>
    <div class="header_top__return ">
        <span class="icon-return"><i class="fa fa-share" aria-hidden="true"></i></span>
        <span class="text-return">60 day return policy</span>
    </div>
</div>